# Generated by Django 3.2.6 on 2021-08-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project image', upload_to='projects/'),
        ),
    ]
