# Generated by Django 3.2.6 on 2021-08-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(default='project image', upload_to='projects/'),
        ),
    ]
