# Generated by Django 3.2.6 on 2021-08-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210817_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='app.Languages'),
        ),
    ]
